name: Action Push Tag
description: Push a Git tag without docker
author: Annulet Consulting
inputs:
  tag:
    description: A Git tag name.
    required: true
  message:
    description: A message for the Git tag.
    required: false
branding:
  icon: search
  color: yellow
runs:
  using: "composite"
  steps:
    - name: push tag
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

        git tag -a "${{ inputs.tag }}" -m "${{ inputs.message }}"
        git push origin "${{ inputs.tag }}"